[2025-01-27T13:06:11.267+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T13:06:11.280+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcp_ingest.load_to_bq manual__2025-01-27T13:06:02.514746+00:00 [queued]>
[2025-01-27T13:06:11.286+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcp_ingest.load_to_bq manual__2025-01-27T13:06:02.514746+00:00 [queued]>
[2025-01-27T13:06:11.286+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 7
[2025-01-27T13:06:11.295+0000] {taskinstance.py:2889} INFO - Executing <Task(BigQueryInsertJobOperator): load_to_bq> on 2025-01-27 13:06:02.514746+00:00
[2025-01-27T13:06:11.303+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'gcp_ingest', 'load_to_bq', 'manual__2025-01-27T13:06:02.514746+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/gcp_ingest_dag.py', '--cfg-path', '/tmp/tmph7hir4a0']
[2025-01-27T13:06:11.305+0000] {standard_task_runner.py:105} INFO - Job 166: Subtask load_to_bq
[2025-01-27T13:06:11.306+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=201) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-27T13:06:11.306+0000] {standard_task_runner.py:72} INFO - Started process 203 to run task
[2025-01-27T13:06:11.339+0000] {task_command.py:467} INFO - Running <TaskInstance: gcp_ingest.load_to_bq manual__2025-01-27T13:06:02.514746+00:00 [running]> on host dacac98f5de2
[2025-01-27T13:06:11.573+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcp_ingest' AIRFLOW_CTX_TASK_ID='load_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T13:06:02.514746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T13:06:02.514746+00:00'
[2025-01-27T13:06:11.575+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T13:06:11.598+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-27T13:06:11.598+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-01-27T13:06:11.599+0000] {credentials_provider.py:402} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-01-27T13:06:11.663+0000] {bigquery.py:2620} INFO - Executing: {'load': {'sourceUris': 'gs://gcs_upload_test_bucket_dtc_de/data_uploaded.parquet', 'destinationTable': {'projectId': 'unique-conquest-448021-n3', 'datasetId': '$(BQ_DATASET)', 'tableId': 'data_uploaded'}, 'sourceFormat': 'PARQUET', 'writeDisposition': 'WRITE_TRUNCATE'}}'
[2025-01-27T13:06:11.664+0000] {bigquery.py:1241} INFO - Inserting job ***_gcp_ingest_load_to_bq_2025_01_27T13_06_02_514746_00_00_c56b8c6dd425ddc57855c1d91aa127da
[2025-01-27T13:06:12.926+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2622, in execute
    job: BigQueryJob | UnknownJob = self._submit_job(hook, self.job_id)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2586, in _submit_job
    return hook.insert_job(
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 553, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1244, in insert_job
    job_api_repr._begin()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/unique-conquest-448021-n3/jobs?prettyPrint=false: Not found: Dataset unique-conquest-448021-n3:$(BQ_DATASET)
[2025-01-27T13:06:12.950+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=gcp_ingest, task_id=load_to_bq, run_id=manual__2025-01-27T13:06:02.514746+00:00, execution_date=20250127T130602, start_date=20250127T130611, end_date=20250127T130612
[2025-01-27T13:06:12.966+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T13:06:12.967+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 166 for task load_to_bq (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/unique-conquest-448021-n3/jobs?prettyPrint=false: Not found: Dataset unique-conquest-448021-n3:$(BQ_DATASET); 203)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2622, in execute
    job: BigQueryJob | UnknownJob = self._submit_job(hook, self.job_id)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2586, in _submit_job
    return hook.insert_job(
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 553, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1244, in insert_job
    job_api_repr._begin()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/unique-conquest-448021-n3/jobs?prettyPrint=false: Not found: Dataset unique-conquest-448021-n3:$(BQ_DATASET)
[2025-01-27T13:06:13.004+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-27T13:06:13.021+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-27T13:06:13.023+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
